# Generated by Django 5.0.3 on 2024-03-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_markedcompetence_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='profession',
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.profession'),
        ),
        migrations.CreateModel(
            name='ProffesionCompitens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comp', models.IntegerField(default=0)),
                ('compit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.competence')),
                ('prof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.profession')),
            ],
        ),
    ]
