# Generated by Django 5.0.3 on 2024-03-18 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_competence_profession_alter_user_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.userprofession'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.userprofession'),
        ),
    ]
