# Generated by Django 5.0.3 on 2024-03-18 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_competence_profession_alter_user_profession'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProffesionCompitens',
            new_name='ProfessionCompitens',
        ),
        migrations.RemoveField(
            model_name='competence',
            name='profession',
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.profession'),
        ),
        migrations.DeleteModel(
            name='UserProfession',
        ),
    ]
